name: Android
on:
  workflow_dispatch:
jobs:
  build:
    name: build flutter for Android
    runs-on: macos-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.0.4"
      WORKING_DIRECTORY: "./flutter_app"
      ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
      ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Decode Keystore
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "${{ secrets.ANDROID_KEYSTORE_FILENAME }}"
          encodedString: ${{ secrets.ANDROID_KEYSTORE }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get
        working-directory: ./flutter_app
      - run: flutter build apk
        working-directory: ./flutter_app
        env:
          ANDROID_KEYSTORE_PATH: ${{ steps.write_file.outputs.filePath }}       
      - run: flutter build appbundle
        working-directory: ./flutter_app
        env:
          ANDROID_KEYSTORE_PATH: ${{ steps.write_file.outputs.filePath }}
      - name: Archive apk artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
      - name: Archive aab artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aab
          path: flutter_app/build/app/outputs/bundle/release/app-release.aab
  release:
    name: release to firebase distribution
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        name: Download aab
        with:
          name: aab
          path: /tmp/aab
      - name: Firebase App Distribution Action for Android
        uses: hasretsariyer/firebase-app-distribution-github-action@v1.0
        with:
          app_id: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          firebase_token: ${{secrets.FIREBASE_TOKEN}}
          app_file: /tmp/aab/app-release.aab